export const garbageDeployCheckProfile = {
  id: 'garbage',
  default: true,
  defaultBaseUrl: 'https://collected.ga/rbage/',
  basePath: '/rbage/',
  previewBaseUrl: 'http://127.0.0.1:5174/rbage/',
  devAppBaseUrl: 'http://127.0.0.1:5176/rbage/',
  sourceSnapshotPath: 'public/data/newsletter-snapshot.json',
  staticSnapshotPath: 'data/newsletter-snapshot.json',
  migrationPaths: [
    'db/instances/garbage/migrations/0001_newsletter.sql',
    'db/migrations/0003_generic_workbench_tables.sql',
    'db/instances/garbage/migrations/0002_workbench_views.sql',
  ],
  smokeFixtureModule: './instances/garbage/deployed-check-smoke-fixture.mjs',
  readinessCheckModule: './instances/garbage/deployed-draft-checks.mjs',
  smokeCommands: [
    'garbage:smoke:api',
    'garbage:smoke:app',
    'garbage:smoke:crawler-dedupe',
    'garbage:smoke:crawler-provenance',
    'garbage:smoke:draft-api',
    'garbage:smoke:draft',
    'garbage:smoke:draft-url',
    'garbage:smoke:ghost',
    'garbage:smoke:grust-watchlist',
    'garbage:smoke:health',
    'garbage:smoke:manual-source',
    'garbage:smoke:public-snapshot',
    'garbage:smoke:queries',
    'garbage:smoke:readiness',
    'garbage:smoke:recency',
    'garbage:smoke:responsive',
    'garbage:smoke:snapshot',
    'garbage:smoke:source-gap-review',
    'garbage:smoke:ulysses',
    'garbage:smoke:view',
    'garbage:smoke:workbench-compat',
    'garbage:audit:grust',
  ],
  removedGenericCommands: [
    'smoke:api',
    'smoke:app',
    'smoke:crawler-dedupe',
    'smoke:crawler-provenance',
    'smoke:draft-api',
    'smoke:draft',
    'smoke:draft-url',
    'smoke:ghost',
    'smoke:grust-watchlist',
    'smoke:health',
    'smoke:manual-source',
    'smoke:public-snapshot',
    'smoke:queries',
    'smoke:readiness',
    'smoke:recency',
    'smoke:responsive',
    'smoke:snapshot',
    'smoke:source-gap-review',
    'smoke:ulysses',
    'smoke:view',
    'audit:grust',
  ],
  publishingCommands: [
    'garbage:draft',
    'garbage:review:gaps',
    'garbage:ulysses:draft',
    'garbage:ulysses:ready',
    'garbage:ghost:draft',
    'garbage:ghost:dry-run',
    'garbage:ghost:ready',
  ],
  compatibilitySqlSmoke: {
    target: 'newsletter',
    sqlPath: '/tmp/verdun-newsletter-load.sql',
    loaderCommand: 'garbage:smoke:loader',
  },
  smokeAllCommands: [
    'garbage:smoke:api',
    'garbage:smoke:crawler-dedupe',
    'garbage:smoke:crawler-provenance',
    'garbage:smoke:health',
    'garbage:smoke:draft-api',
    'garbage:smoke:draft',
    'garbage:smoke:draft-url',
    'garbage:smoke:ghost',
    'garbage:smoke:grust-watchlist',
    'garbage:smoke:manual-source',
    'garbage:smoke:public-snapshot',
    'garbage:smoke:queries',
    'garbage:smoke:readiness',
    'garbage:smoke:recency',
    'garbage:smoke:snapshot',
    'garbage:smoke:source-gap-review',
    'garbage:smoke:ulysses',
    'garbage:smoke:view',
    'garbage:smoke:workbench-compat',
  ],
  uiSmokeCommands: [
    'garbage:smoke:app',
    'garbage:smoke:responsive',
  ],
  minRecords: 23,
  minCollectionPlans: 23,
  requiredSubjects: ['Pydantic', 'LakeSail', 'Apache Arrow', 'DataFusion', 'Delta Lake', 'Turso', 'LanceDB', 'HelixDB', 'SurrealDB', 'pgGraph', 'Garde', 'zod-rs'],
  requiredPlans: ['BAML', 'DSPy', 'Apache Arrow', 'DataFusion', 'Delta Lake', 'Ibis', 'Dagster', 'Garde', 'zod-rs'],
  draft: {
    apiPath: '/api/garbage/newsletter/draft',
    checkModule: './instances/garbage/deployed-draft-checks.mjs',
    markdownIncludes: ['Strongly Typed AI/Data Notes', '## Sources watched'],
    manifestSnapshotInput: 'api/garbage/newsletter/items',
  },
}
