use anyhow::{Context, Result};
use chrono::{DateTime, Duration, Utc};
use clap::{Parser, Subcommand};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::{fs, path::PathBuf};

#[derive(Parser)]
#[command(author, version, about = "Verdun newsletter crawler and loader")]
struct Cli {
    #[command(subcommand)]
    command: CommandKind,
}

#[derive(Subcommand)]
enum CommandKind {
    Collect {
        #[arg(long, default_value = "crawler/config/watchlist.toml")]
        config: PathBuf,
        #[arg(long, default_value = "crawler/data/items.json")]
        out: PathBuf,
    },
    ExportSql {
        #[arg(long, default_value = "crawler/data/items.json")]
        input: PathBuf,
        #[arg(long, default_value = "/tmp/verdun-newsletter-load.sql")]
        out: PathBuf,
    },
    Verify {
        #[arg(long, default_value = "crawler/config/watchlist.toml")]
        config: PathBuf,
    },
}

#[derive(Debug, Deserialize)]
struct Watchlist {
    theme: String,
    projects: Vec<Project>,
    sources: Vec<Source>,
}

#[derive(Debug, Deserialize)]
struct Project {
    name: String,
    topic: String,
    homepage: String,
    keywords: Vec<String>,
}

#[derive(Debug, Deserialize, Clone)]
struct Source {
    name: String,
    kind: String,
    url: String,
}

#[derive(Debug, Serialize, Deserialize)]
struct NewsItem {
    id: String,
    title: String,
    source: String,
    source_kind: String,
    url: String,
    published_at: DateTime<Utc>,
    project: String,
    topic: String,
    summary: String,
    why_it_matters: String,
    tags: Vec<String>,
    score: i32,
    raw_json: serde_json::Value,
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    match cli.command {
        CommandKind::Collect { config, out } => collect(config, out),
        CommandKind::ExportSql { input, out } => export_sql(input, out),
        CommandKind::Verify { config } => verify(config),
    }
}

fn collect(config: PathBuf, out: PathBuf) -> Result<()> {
    let watchlist = read_watchlist(&config)?;
    let items = seed_items(&watchlist);
    if let Some(parent) = out.parent() {
        fs::create_dir_all(parent).with_context(|| format!("creating {}", parent.display()))?;
    }
    fs::write(&out, serde_json::to_string_pretty(&items)?).with_context(|| format!("writing {}", out.display()))?;
    println!("wrote {} newsletter items to {}", items.len(), out.display());
    Ok(())
}

fn export_sql(input: PathBuf, out: PathBuf) -> Result<()> {
    let items: Vec<NewsItem> = serde_json::from_slice(&fs::read(&input).with_context(|| format!("reading {}", input.display()))?)?;
    let mut sql = String::from("-- Generated by verdun-crawler export-sql\nbegin;\n");
    for item in &items {
        sql.push_str("insert into newsletter_items (\n");
        sql.push_str("  id, title, source, source_kind, url, published_at, project, topic, summary, why_it_matters, tags, score, raw_json, updated_at\n");
        sql.push_str(") values (");
        sql.push_str(&sql_string(&item.id));
        sql.push_str(", ");
        sql.push_str(&sql_string(&item.title));
        sql.push_str(", ");
        sql.push_str(&sql_string(&item.source));
        sql.push_str(", ");
        sql.push_str(&sql_string(&item.source_kind));
        sql.push_str(", ");
        sql.push_str(&sql_string(&item.url));
        sql.push_str(", ");
        sql.push_str(&sql_string(&item.published_at.to_rfc3339()));
        sql.push_str("::timestamptz, ");
        sql.push_str(&sql_string(&item.project));
        sql.push_str(", ");
        sql.push_str(&sql_string(&item.topic));
        sql.push_str(", ");
        sql.push_str(&sql_string(&item.summary));
        sql.push_str(", ");
        sql.push_str(&sql_string(&item.why_it_matters));
        sql.push_str(", ");
        sql.push_str(&sql_text_array(&item.tags));
        sql.push_str(", ");
        sql.push_str(&item.score.to_string());
        sql.push_str(", ");
        sql.push_str(&sql_string(&serde_json::to_string(&item.raw_json)?));
        sql.push_str("::jsonb, now())\n");
        sql.push_str("on conflict (id) do update set\n");
        sql.push_str("  title = excluded.title,\n  source = excluded.source,\n  source_kind = excluded.source_kind,\n  url = excluded.url,\n");
        sql.push_str("  published_at = excluded.published_at,\n  project = excluded.project,\n  topic = excluded.topic,\n");
        sql.push_str("  summary = excluded.summary,\n  why_it_matters = excluded.why_it_matters,\n  tags = excluded.tags,\n");
        sql.push_str("  score = excluded.score,\n  raw_json = excluded.raw_json,\n  updated_at = excluded.updated_at;\n\n");
    }
    sql.push_str("commit;\n");
    fs::write(&out, sql).with_context(|| format!("writing {}", out.display()))?;
    println!("wrote SQL load for {} items to {}", items.len(), out.display());
    Ok(())
}

fn verify(config: PathBuf) -> Result<()> {
    let watchlist = read_watchlist(&config)?;
    anyhow::ensure!(!watchlist.projects.is_empty(), "watchlist must include projects");
    anyhow::ensure!(!watchlist.sources.is_empty(), "watchlist must include sources");
    anyhow::ensure!(watchlist.projects.iter().any(|project| project.name == "Pydantic"), "Pydantic must be tracked");
    anyhow::ensure!(watchlist.projects.iter().any(|project| project.name == "LakeSail"), "LakeSail must be tracked");
    anyhow::ensure!(watchlist.sources.iter().any(|source| source.name == "Hacker News"), "Hacker News must be tracked");
    println!(
        "verified {} projects and {} sources for {}",
        watchlist.projects.len(),
        watchlist.sources.len(),
        watchlist.theme
    );
    Ok(())
}

fn read_watchlist(path: &PathBuf) -> Result<Watchlist> {
    let text = fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
    toml::from_str(&text).with_context(|| format!("parsing {}", path.display()))
}

fn seed_items(watchlist: &Watchlist) -> Vec<NewsItem> {
    let source = watchlist
        .sources
        .iter()
        .find(|candidate| candidate.name == "Hacker News")
        .cloned()
        .unwrap_or_else(|| watchlist.sources[0].clone());
    watchlist
        .projects
        .iter()
        .enumerate()
        .map(|(index, project)| project_item(project, &source, index))
        .collect()
}

fn project_item(project: &Project, source: &Source, index: usize) -> NewsItem {
    let published_at = Utc::now() - Duration::days(index as i64);
    let title = format!("{} belongs in this week's typed AI/data systems watch", project.name);
    let summary = format!(
        "{} is being tracked for {} signals around {}.",
        project.name,
        project.topic,
        project.keywords.join(", ")
    );
    let why_it_matters = format!(
        "{} helps explain where typed contracts, local execution, and practical AI/data systems are converging.",
        project.name
    );
    let id = stable_id(&project.name, &project.homepage);
    NewsItem {
        id,
        title,
        source: source.name.clone(),
        source_kind: source.kind.clone(),
        url: project.homepage.clone(),
        published_at,
        project: project.name.clone(),
        topic: project.topic.clone(),
        summary,
        why_it_matters,
        tags: project.keywords.iter().take(4).cloned().collect(),
        score: 90 - (index as i32 * 3),
        raw_json: serde_json::json!({
            "homepage": project.homepage,
            "source_url": source.url,
            "collection_stage": "watchlist-seed"
        }),
    }
}

fn stable_id(project: &str, url: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(project.as_bytes());
    hasher.update(b"\n");
    hasher.update(url.as_bytes());
    let digest = hasher.finalize();
    format!("{}-{:x}", slug(project), &digest[..6].iter().fold(0_u64, |acc, byte| (acc << 8) | u64::from(*byte)))
}

fn slug(value: &str) -> String {
    value
        .to_lowercase()
        .chars()
        .map(|character| if character.is_ascii_alphanumeric() { character } else { '-' })
        .collect::<String>()
        .split('-')
        .filter(|part| !part.is_empty())
        .collect::<Vec<_>>()
        .join("-")
}

fn sql_string(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

fn sql_text_array(values: &[String]) -> String {
    let values = values.iter().map(|value| sql_string(value)).collect::<Vec<_>>().join(", ");
    format!("array[{}]::text[]", values)
}
